name: Markdown Lint

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14  # Change this to your Node.js version

    - name: Install dependencies
      run: npm ci

    - name: Run Markdown Lint
      run: npm run lint:markdownlint
